modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="better_steel"
version="1.20-1.0.1"
displayName="Better Steel"
logoFile="better_steel.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Makes steel much easier to attain for any tech mods.
'''

[[dependencies.better_steel]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_steel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_steel]]
    modId="lemon_core"
    mandatory=true
    versionRange="[1.20-1.0.7,)"
    ordering="NONE"
    side="BOTH"